// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjmxxgewmooobsuuysms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbXh4Z2V3bW9vb2JzdXV5c21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDAzMjYsImV4cCI6MjA2NjIxNjMyNn0.3OnkqJQKqBzaRhZXl6GBr3WGLswyJ94ItQ1Ki3rfPi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);